spring:
  profiles:
    active: production
  datasource:
    url: ${JDBC_DATABASE_URL:postgres://ec2-54-74-156-137.eu-west-1.compute.amazonaws.com:5432/d91q9ftde9ils8}
    user: ${JDBC_DATABASE_USERNAME:vvhhjmffrrskih}
    password: ${JDBC_DATABASE_PASSWORD:0899c758db5d19ba11262045a9144ff0c2ac761c1f4b44bb4225d633ec0a4c0f}